/**
 * Each source from Pinecone DB that contributed to the answer -Used
 */
export interface ContextUsedItem {
  id: string;         // ID of the Pinecone vector / chunk
  score: number;      // Similarity score (0-1)
  page: number | null; // Optional page number from source
}

/**
 * The assistant content returned from LLM - Used
 */
export interface AssistantContent {
  answer: string;       // Short factual answer generated by LLM
  suggestions?: string[]; // Optional suggested follow-up questions
}

/**
 * The full result returned from answerWithHospitalContext - Used
 */
export interface AnswerWithContextResult {
  assistantContent: AssistantContent;  // LLM answer + suggestions
  contextUsed: ContextUsedItem[];      // Array of sources used
}

// Used
export type SearchHit = {
  _id: string;
  _score: number;
  fields?: {
    text?: string;
    page?: number;
  };
};

// Used
export type Namespace = {
  searchRecords: (args: {
    query: {
      topK: number;
      inputs: { text: string };
    };
    fields: string[];
  }) => Promise<{
    result?: {
      hits?: SearchHit[];
    };
  }>;
};


// Used 
export type AnswerWithContextParams = {
  content: string;
  namespace: Namespace;
  generateAnswer: (query: string, context: string) => Promise<{
    answer: string;
    suggestions?: string[];
  }>;
  topK?: number;
};
